host: 0.0.0.0
port: 4000
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jean-Luc Chamaa
description: >- # this means to ignore newlines until "baseurl:"
 Jean-Luc is a mechanical engineer by training, a software engineer by passion, and a full-on nerd by birth. 
bio: Software Engineer, UCLA Mechanical Engineering Alumnus, maker, burrito connoisseur, and undisputed bona-fide nerd. 
email: jlchamaa@gmail.com
facebook: jlchamaa
linkedin: jlchamaa
instagram: jlchamaa
github-url: jlchamaa
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/myProf.png"
background: '/assets/img/mysmallbg.jpg'
tiled_bg:  false   # Set this true if you want to tile your background image, otherwise it will be covered

# Build settings
markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:path/
  hobbies:
    output: true
    permalink: /hobbies/:path/
  experience:
    output: true
    permalink: /experience/:path/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
